/*
 * PhishWard - A proactive phishing and threat analysis tool.
 * Copyright (C) 2026 ju57a7ouc4n
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.ju57a7ouc4n.phishlab.model.events;

/**
 * Immutable event object representing an error that should be notified to the user.
 * Encapsulates the error details generated by the Model layer to be broadcasted
 * to registered listeners (typically the Controller).
 *
 * @author ju57a7ouc4n
 * @version 1.0
 */

public class UserHandledError {
	private String title;
	private String message;
	private Exception exception;
	
	public UserHandledError(String title, String message, Exception e) {
		this.title = title;
		this.message = message;
		this.exception = e;
	}

	public String getTitle() {
		return title;
	}

	public String getMessage() {
		return message;
	}

	public Exception getException() {
		return exception;
	}
	
}
