/*
 * PhishWard - A proactive phishing and threat analysis tool.
 * Copyright (C) 2026 ju57a7ouc4n
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.ju57a7ouc4n.phishlab.controller;

import com.ju57a7ouc4n.phishlab.model.dao.RuleDAO;
import com.ju57a7ouc4n.phishlab.model.entities.AnalysisResult;
import com.ju57a7ouc4n.phishlab.model.entities.Rule;
import com.ju57a7ouc4n.phishlab.model.entities.RuleType;
import com.ju57a7ouc4n.phishlab.model.entities.UrlTarget;
import com.ju57a7ouc4n.phishlab.model.network.HttpAnalyzer;
import com.ju57a7ouc4n.phishlab.model.network.PhishTankClient;
import com.ju57a7ouc4n.phishlab.model.events.ErrorListener;
import com.ju57a7ouc4n.phishlab.model.events.UserHandledError;

/**
 * Central controller of the MVC architecture for PhishWard.
 * Moderates communication between the intelligence layer (Network/OSINT),
 * the local database, and the future graphical user interface.
 *
 * @author ju57a7ouc4n
 * @version 1.0
 */
public class PhishWardController implements ErrorListener {
    private RuleDAO ruleDao;
    private HttpAnalyzer httpAnalyzer;
    private PhishTankClient phishTankClient;

    public PhishWardController() {
        this.ruleDao = new RuleDAO();
        this.httpAnalyzer = new HttpAnalyzer();
        this.phishTankClient = new PhishTankClient();
        this.ruleDao.addErrorListener(this);
        this.httpAnalyzer.addErrorListener(this);
        this.phishTankClient.addErrorListener(this);
    }

    /**
     * Method required by the ErrorListener interface.
     * Catches any error event generated by the lower layers (Network or Database).
     * Isolates the View from the technical complexity of exception handling.
     *
     * @param error The immutable event object containing the error details.
     */
    @Override
    public void anErrorOcurred(UserHandledError error) {
        /*****/
    }
    
    /**
     * Executes the complete analysis pipeline for a given URL.
     * Processes the input through sanitization, local database caching,
     * network intelligence gathering, and OSINT verification.
     *
     * @param rawUrl The raw string input provided by the user.
     * @return An AnalysisResult object containing the threat score, evidence, and risk level.
     */
    public AnalysisResult processUrl(String rawUrl) {
        UrlTarget target = new UrlTarget(rawUrl);
        AnalysisResult result = new AnalysisResult(target);
        if (!target.isValid()) {
            result.addThreatScore(0, "Invalid URL format. Analysis aborted.");
            return result; 
        }
        Rule foundRule = this.ruleDao.findRuleByIndicator(target.getDomain());
        if(foundRule != null) {
        	if(foundRule.getListType()== RuleType.WHITELIST) {
        		result.addThreatScore(0, "URL Appears in Local Whitelist.");
        		result.setFoundInLocalList(true);
        	}
        	else {
        		result.addThreatScore(100, "URL Appears in Local Blacklist.");
        		result.setFoundInLocalList(true);
        	}
        	return result;
        }
        result.setResolvedIp(this.httpAnalyzer.resolveIp(target));
        result.setHeaders(httpAnalyzer.fetchHeaders(target));
        boolean hasHsts = false;
        boolean hasXFrame = false;
        boolean hasCsp = false;
        boolean hasXContentType = false;
        boolean injectsCookies = false;
        for (String key : result.getHeaders().keySet()) {
            String lowerKey = key.toLowerCase();
            if (lowerKey.equals("strict-transport-security")) hasHsts = true;
            else if (lowerKey.equals("x-frame-options")) hasXFrame = true;
            else if (lowerKey.equals("content-security-policy")) hasCsp = true;
            else if (lowerKey.equals("x-content-type-options")) hasXContentType = true;
            else if (lowerKey.equals("set-cookie")) injectsCookies = true;
        }
        if (!hasHsts) result.addThreatScore(15, "Missing Strict-Transport-Security (HSTS) header.");
        if (!hasXFrame) result.addThreatScore(10, "Missing X-Frame-Options header.");
        if (!hasCsp) result.addThreatScore(10, "Missing Content-Security-Policy (CSP) header.");
        if (!hasXContentType) result.addThreatScore(5, "Missing X-Content-Type-Options header.");
        if (injectsCookies) {
            result.setSetsCookies(true);
            result.addThreatScore(10, "Server injects tracking or session cookies (Set-Cookie).");
        }
        if(this.phishTankClient.isPhishing(target)) {
        	result.addThreatScore(80, "Reported in Phishtank.");
        }
        return result;
    }
}