/*
 * PhishWard - A proactive phishing and threat analysis tool.
 * Copyright (C) 2026 ju57a7ouc4n
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.ju57a7ouc4n.phishlab.controller;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import com.ju57a7ouc4n.phishlab.engine.AnalysisEngine;
import com.ju57a7ouc4n.phishlab.model.entities.AnalysisResult;
import com.ju57a7ouc4n.phishlab.model.entities.RuleType;
import com.ju57a7ouc4n.phishlab.view.MainView;
import com.ju57a7ouc4n.phishlab.model.events.AnalysisProgressListener;
import com.ju57a7ouc4n.phishlab.model.events.ErrorListener;
import com.ju57a7ouc4n.phishlab.model.events.UserHandledError;

/**
 * Central controller of the MVC architecture for PhishWard.
 * Moderates communication between the intelligence layer (Network/OSINT),
 * the local database, and the future graphical user interface.
 *
 * @author ju57a7ouc4n
 * @version 1.0
 */
public class PhishWardController implements ErrorListener, ActionListener, AnalysisProgressListener {
    private MainView view;
    private AnalysisEngine engine;
    private AnalysisResult result = null;

    public PhishWardController() {
        this.engine = AnalysisEngine.getInstance();
        this.engine.addErrorListener(this);
        this.engine.setProgressListener(this);
    }

    public void setView(MainView view) {
        this.view = view;
        this.engine.setApiKey(this.view.getApiKey());
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        String command = e.getActionCommand();

        if (command.equals("ANALYZE")) {
            startAnalysisPipeline();
        } else if (this.result != null && command.equals("WHITELIST")) {
            this.engine.addDomainToList(result.getTarget().getDomain(), RuleType.WHITELIST, view.getReason());
            this.view.appendToConsole("[+] Added to Whitelist.");
        } else if (this.result != null && command.equals("BLACKLIST")) {
        	this.engine.addDomainToList(result.getTarget().getDomain(), RuleType.BLACKLIST, "Valid Domain");
        	this.view.appendToConsole("[-] Added to Blacklist.");
        }
    }
    
    private void startAnalysisPipeline() {
        view.setUiLocked(true);
        view.setListButtonsEnabled(false);
        view.updateScoreLabel(0, Color.BLACK);
        this.result = this.engine.processUrl(view.getTargetUrl());
        this.updateViewWithResult(result);
    }
    
    /**
     * Catches any error event generated by the lower layers (Network or Database).
     * Delegates the display of the error to the View via a pop-up and logs it.
     *
     * @param error The immutable event object containing the error details.
     */
    @Override
    public void anErrorOcurred(UserHandledError error) {
        if (this.view != null) {
            this.view.appendToConsole("\n[!!!] CRITICAL EXCEPTION CAUGHT [!!!]");
            this.view.appendToConsole("[!] Module: " + error.getTitle());
            this.view.appendToConsole("[!] Details: " + error.getMessage());
            this.view.appendToConsole("=========================================\n");
            this.view.showErrorDialog(error.getTitle(), error.getMessage());
            this.view.setUiLocked(false);
        }
    }

	@Override
	public void onProgressUpdate(String message) {
            if (this.view != null) 
                this.view.appendToConsole(message);
	}
	
	private void updateViewWithResult(AnalysisResult result) {
        view.appendToConsole("\n[+] Pipeline completed successfully.\n");
        view.appendToConsole(result.getScoreBreakdown().toString());
        int score = result.getThreatScore();
        java.awt.Color scoreColor = (score == 0) ? new java.awt.Color(0, 150, 0) : (score < 50) ? new java.awt.Color(200, 100, 0) : java.awt.Color.RED;
        view.updateScoreLabel(score, scoreColor);
        view.setListButtonsEnabled(true);
        view.setUiLocked(false); 
    }
}